try:
    x = int(input('input an integer'))
    print(x)
except:
    print('somthing went wrong')
finally:
    print('try except finished')        

